### ISSUE TITLE
Crash related to the graphics backend

### ISSUE THREAD

**Issue by Lazin3ss** [ikemen-engine/Ikemen-GO#1262]
### Describe the bug

While passively running Ikemen GO, the engine can randomly crash without opening any error message window. A log can be gathered when running the engine through the command line, but the crash is unpredictable. Gonna paste the crash log here.

```
runtime: bad pointer in frame github.com/go-gl/gl/v2.1/gl.VertexAttribPointer.func1 at 0xc0008df8f0: 0x8
fatal error: invalid pointer found on stack
 
runtime stack:
runtime.throw({0x89bc90?, 0x7bffa0?})
        runtime/panic.go:1047 +0x65 fp=0x25903ff330 sp=0x25903ff300 pc=0x3a9245
runtime.adjustpointers(0x25903ff738?, 0x88c8c?, 0xa31fee?, {0xb15918?, 0x7bffa0?})
        runtime/stack.go:630 +0x1d0 fp=0x25903ff398 sp=0x25903ff330 pc=0x3be250
runtime.adjustframe(0x25903ff738, 0x25903ff828)
        runtime/stack.go:672 +0xc9 fp=0x25903ff428 sp=0x25903ff398 pc=0x3be369
runtime.gentraceback(0x7ffd00000000?, 0x27c3e5898?, 0x1713f4ccccd?, 0x17100000008?, 0x0, 0x0, 0x7fffffff, 0x8a9220, 0x0?, 0x0)
        runtime/traceback.go:334 +0xd0f fp=0x25903ff7a0 sp=0x25903ff428 pc=0x3c9f0f
runtime.copystack(0xc000034000, 0xffffffffffffffff?)
        runtime/stack.go:932 +0x2f5 fp=0x25903ff958 sp=0x25903ff7a0 pc=0x3beb75
runtime.shrinkstack(0xc000034000)
        runtime/stack.go:1214 +0x126 fp=0x25903ff978 sp=0x25903ff958 pc=0x3bfa46
runtime.newstack()
        runtime/stack.go:1062 +0x3aa fp=0x25903ffb30 sp=0x25903ff978 pc=0x3bf00a
runtime.morestack()
        runtime/asm_amd64.s:570 +0x93 fp=0x25903ffb38 sp=0x25903ffb30 pc=0x3d4913
 
goroutine 1 [running, locked to thread]:
runtime.cgoCheckArg(0x80d560?, 0x8?, 0x0?, 0x1?, {0x8a1867?, 0x29?})
        runtime/cgocall.go:447 +0x52a fp=0xc0008df868 sp=0xc0008df860 pc=0x37558a
runtime.cgoCheckPointer({0x80d560, 0x8}, {0x0, 0x0})
        runtime/cgocall.go:437 +0x156 fp=0xc0008df8b0 sp=0xc0008df868 pc=0x374ff6
github.com/go-gl/gl/v2.1/gl.VertexAttribPointer.func1(0x55f612?, 0x0?, 0x7a03e0?, 0x0, 0xd8d938?, 0xc000d8d938?)
        github.com/go-gl/gl@v0.0.0-20211210172815-726fda9656d6/v2.1/gl/package.go:28190 +0x51 fp=0xc0008df908 sp=0xc0008df8b0 pc=0x5639b1
github.com/go-gl/gl/v2.1/gl.VertexAttribPointer(0x73250b80?, 0x0?, 0x1?, 0x2?, 0x3?, 0xc000d8d968?)
        github.com/go-gl/gl@v0.0.0-20211210172815-726fda9656d6/v2.1/gl/package.go:28190 +0x19 fp=0xc0008df938 sp=0xc0008df908 pc=0x5638f9
github.com/fyne-io/gl-js.VertexAttribPointer(...)
        github.com/fyne-io/gl-js@v0.0.0-20220802150000-8e339395f381/gl_opengl.go:1218
main.(*Renderer).SetPipeline(0xb85d00, 0x0?, 0x3f80000000000000?, 0x0?)
        github.com/ikemen-engine/Ikemen-GO/src/render_gl.go:336 +0x22e fp=0xc0008df988 sp=0xc0008df938 pc=0x71d3ce
main.RenderSprite.func1(0xc000d8dac8?, 0x71d674?, 0x7ffd83e85c80?, 0x3f800000)
        github.com/ikemen-engine/Ikemen-GO/src/render.go:296 +0xa9 fp=0xc0008dfa98 sp=0xc0008df988 pc=0x71a389
main.renderWithBlending(0xc000d8dc10, 0xc11?, 0x0?)
        github.com/ikemen-engine/Ikemen-GO/src/render.go:343 +0xbd fp=0xc0008dfad8 sp=0xc0008dfa98 pc=0x71a79d
main.RenderSprite({0xc0007725a0, 0xc00125b548, {0x4, 0x6}, 0x42d00000, 0xc1200000, {0x0, 0x0, 0x0, 0x0}, ...})
        github.com/ikemen-engine/Ikemen-GO/src/render.go:294 +0x591 fp=0xc0008dfc98 sp=0xc0008dfad8 pc=0x71a291
main.(*Fnt).drawChar(0xc0006f2090, 0x42500000, 0x40a00000, 0x3f800000, 0x3f800000, 0x0, 0x0?, 0x61, {0xc0000f6400, 0x100, ...}, ...)
        github.com/ikemen-engine/Ikemen-GO/src/font.go:465 +0x558 fp=0xc0008dfdc8 sp=0xc0008dfc98 pc=0x6d7278
main.(*Fnt).DrawText(0xc0006f2090, {0xc0008ce633, 0xb}, 0x41600000, 0x41200000, 0x3f800000, 0x3f800000, 0x0?, 0x1, 0xc000000000000000?, ...)
        github.com/ikemen-engine/Ikemen-GO/src/font.go:520 +0x5d1 fp=0xc0008dfe88 sp=0xc0008dfdc8 pc=0x6d7a91
main.(*Fnt).Print(0xc000ce2110?, {0xc0008ce633?, 0x0?}, 0x80000000?, 0x0?, 0xd8df80?, 0xc0?, 0xd8df88?, 0xc0?, 0x664e13?, ...)
        github.com/ikemen-engine/Ikemen-GO/src/font.go:475 +0x58 fp=0xc0008dfee0 sp=0xc0008dfe88 pc=0x6d7418
main.(*Layout).DrawText(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, {0xc0008ce633?, 0x0?}, 0x0?, 0x0?, 0x0?, ...)
        github.com/ikemen-engine/Ikemen-GO/src/common.go:667 +0xcf fp=0xc0008dff40 sp=0xc0008dfee0 pc=0x664f4f
main.(*LifeBarName).draw(0xc000cf9200, 0xe450?, 0x1?, {0x7dbe98, 0xa, 0xa?}, 0x0)
        github.com/ikemen-engine/Ikemen-GO/src/lifebar.go:1179 +0xe7 fp=0xc0008dffd8 sp=0xc0008dff40 pc=0x6f5507
main.(*Lifebar).draw(0x7dbe80, 0x0)
        github.com/ikemen-engine/Ikemen-GO/src/lifebar.go:3961 +0xb5d fp=0xc0008e0170 sp=0xc0008dffd8 pc=0x713d3d
main.(*System).draw(0x7dbc80, 0x0, 0x0, 0x3f800000)
        github.com/ikemen-engine/Ikemen-GO/src/system.go:1521 +0x474 fp=0xc0008e0220 sp=0xc0008e0170 pc=0x766a14
main.(*System).fight(0x7dbc80)
        github.com/ikemen-engine/Ikemen-GO/src/system.go:2096 +0x1a73 fp=0xc0008e0ec0 sp=0xc0008e0220 pc=0x769893
main.systemScriptInit.func57.2()
        github.com/ikemen-engine/Ikemen-GO/src/script.go:945 +0x578 fp=0xc0008e1268 sp=0xc0008e0ec0 pc=0x727df8
main.systemScriptInit.func57(0xc000056210)
        github.com/ikemen-engine/Ikemen-GO/src/script.go:990 +0x3d3 fp=0xc0008e14c0 sp=0xc0008e1268 pc=0x724253
github.com/yuin/gopher-lua.callGFunction(0xc000056210, 0x0)
        github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/vm.go:202 +0x37 fp=0xc0008e1528 sp=0xc0008e14c0 pc=0x550397
github.com/yuin/gopher-lua.init.3.func26(0xc000056210, 0x18280083?, 0xc000211000?)
        github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/vm.go:821 +0x379 fp=0xc0008e1698 sp=0xc0008e1528 pc=0x553319
github.com/yuin/gopher-lua.mainLoop(0xc000056210, 0xc0003499c0?)
        github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/vm.go:31 +0xfa fp=0xc0008e16c8 sp=0xc0008e1698 pc=0x54ff5a
github.com/yuin/gopher-lua.(*LState).callR(0xc000056210, 0x0, 0xffffffffffffffff, 0xc0000ca5d0?)
        github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:1211 +0x1b4 fp=0xc0008e17c0 sp=0xc0008e16c8 pc=0x541714
github.com/yuin/gopher-lua.(*LState).Call(...)
        github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:1967
github.com/yuin/gopher-lua.(*LState).PCall(0xc000056210, 0x0, 0xc0003499c0?, 0x0)
        github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:2030 +0x145 fp=0xc0008e1850 sp=0xc0008e17c0 pc=0x545285
github.com/yuin/gopher-lua.(*LState).DoFile(0xc000056210, {0xc000018810?, 0x0?})
        github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/auxlib.go:396 +0x6b fp=0xc0008e1880 sp=0xc0008e1850 pc=0x519aeb
main.main()
        github.com/ikemen-engine/Ikemen-GO/src/main.go:90 +0x218 fp=0xc0008e1f80 sp=0xc0008e1880 pc=0x714c38
runtime.main()
        runtime/proc.go:250 +0x1fe fp=0xc0008e1fe0 sp=0xc0008e1f80 pc=0x3ab97e
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc0008e1fe8 sp=0xc0008e1fe0 pc=0x3d6b41
 
goroutine 2 [force gc (idle), 263 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:363 +0xd6 fp=0xc000037fb0 sp=0xc000037f90 pc=0x3abd16
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.forcegchelper()
        runtime/proc.go:302 +0xb1 fp=0xc000037fe0 sp=0xc000037fb0 pc=0x3abbb1
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc000037fe8 sp=0xc000037fe0 pc=0x3d6b41
created by runtime.init.6
        runtime/proc.go:290 +0x25
 
goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:363 +0xd6 fp=0xc000039f90 sp=0xc000039f70 pc=0x3abd16
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.bgsweep(0x0?)
        runtime/mgcsweep.go:297 +0xd7 fp=0xc000039fc8 sp=0xc000039f90 pc=0x395fb7
runtime.gcenable.func1()
        runtime/mgc.go:178 +0x26 fp=0xc000039fe0 sp=0xc000039fc8 pc=0x38ab06
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc000039fe8 sp=0xc000039fe0 pc=0x3d6b41
created by runtime.gcenable
        runtime/mgc.go:178 +0x6b
 
goroutine 4 [GC scavenge wait]:
runtime.gopark(0x66b67bc53ac74?, 0x5b9b90?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:363 +0xd6 fp=0xc000047f70 sp=0xc000047f50 pc=0x3abd16
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.(*scavengerState).park(0xb85f60)
        runtime/mgcscavenge.go:389 +0x53 fp=0xc000047fa0 sp=0xc000047f70 pc=0x393ff3
runtime.bgscavenge(0x0?)
        runtime/mgcscavenge.go:622 +0x65 fp=0xc000047fc8 sp=0xc000047fa0 pc=0x394605
runtime.gcenable.func2()
        runtime/mgc.go:179 +0x26 fp=0xc000047fe0 sp=0xc000047fc8 pc=0x38aaa6
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc000047fe8 sp=0xc000047fe0 pc=0x3d6b41
created by runtime.gcenable
        runtime/mgc.go:179 +0xaa
 
goroutine 18 [finalizer wait]:
runtime.gopark(0x0?, 0x8a8ca0?, 0x60?, 0x1?, 0x1000000010?)
        runtime/proc.go:363 +0xd6 fp=0xc00003be28 sp=0xc00003be08 pc=0x3abd16
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.runfinq()
        runtime/mfinal.go:180 +0x10f fp=0xc00003bfe0 sp=0xc00003be28 pc=0x389c0f
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc00003bfe8 sp=0xc00003bfe0 pc=0x3d6b41
created by runtime.createfing
        runtime/mfinal.go:157 +0x45
 
goroutine 5 [sleep]:
runtime.gopark(0x66b7d4831ff24?, 0x1?, 0x0?, 0x0?, 0x2500?)
        runtime/proc.go:363 +0xd6 fp=0xc000049e18 sp=0xc000049df8 pc=0x3abd16
time.Sleep(0x516155)
        runtime/time.go:195 +0x13c fp=0xc000049e58 sp=0xc000049e18 pc=0x3d37fc
github.com/hajimehoshi/oto.(*driverWriter).Write(0xc00001e660, {0xc0002f2000?, 0x8000?, 0x8000?})
        github.com/hajimehoshi/oto@v0.7.1/context.go:155 +0x229 fp=0xc000049f00 sp=0xc000049e58 pc=0x5bf209
io.copyBuffer({0x93f838, 0xc00001e660}, {0x93f878, 0xc00004a600}, {0x0, 0x0, 0x0})
        io/io.go:429 +0x204 fp=0xc000049f80 sp=0xc000049f00 pc=0x3e2464
io.Copy(...)
        io/io.go:386
github.com/hajimehoshi/oto.NewContext.func1()
        github.com/hajimehoshi/oto@v0.7.1/context.go:85 +0x49 fp=0xc000049fe0 sp=0xc000049f80 pc=0x5bed89
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc000049fe8 sp=0xc000049fe0 pc=0x3d6b41
created by github.com/hajimehoshi/oto.NewContext
        github.com/hajimehoshi/oto@v0.7.1/context.go:84 +0x2bc
 
goroutine 6 [select]:
runtime.gopark(0xc000043ed0?, 0x2?, 0x68?, 0xf6?, 0xc000043e84?)
        runtime/proc.go:363 +0xd6 fp=0xc000043cf0 sp=0xc000043cd0 pc=0x3abd16
runtime.selectgo(0xc000043ed0, 0xc000043e80, 0x5927c5?, 0x1, 0xc000043e68?, 0x1)
        runtime/select.go:328 +0x7dc fp=0xc000043e30 sp=0xc000043cf0 pc=0x3ba0bc
io.(*pipe).write(0xc00004c420, {0xc000246000, 0x2000, 0x2000})
        io/pipe.go:86 +0x212 fp=0xc000043f08 sp=0xc000043e30 pc=0x3e30f2
io.(*PipeWriter).Write(0x200?, {0xc000246000?, 0x0?, 0x600?})
        io/pipe.go:165 +0x25 fp=0xc000043f38 sp=0xc000043f08 pc=0x3e3565
github.com/hajimehoshi/oto.(*Player).Write(0xc00001e6c0, {0xc000246000, 0x2000, 0x2000})
        github.com/hajimehoshi/oto@v0.7.1/player.go:66 +0x76 fp=0xc000043f90 sp=0xc000043f38 pc=0x5c00d6
github.com/samhocevar/beep/speaker.update()
        github.com/samhocevar/beep@v1.1.1-0.20230406132407-3fba40ddabcc/speaker/speaker.go:129 +0xc5 fp=0xc000043fc0 sp=0xc000043f90 pc=0x5c1845
github.com/samhocevar/beep/speaker.Init.func1()
        github.com/samhocevar/beep@v1.1.1-0.20230406132407-3fba40ddabcc/speaker/speaker.go:52 +0x1b fp=0xc000043fe0 sp=0xc000043fc0 pc=0x5c11db
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc000043fe8 sp=0xc000043fe0 pc=0x3d6b41
created by github.com/samhocevar/beep/speaker.Init
        github.com/samhocevar/beep@v1.1.1-0.20230406132407-3fba40ddabcc/speaker/speaker.go:48 +0x1e9
 
goroutine 20 [GC worker (idle)]:
runtime.gopark(0x66b7d3a88e680?, 0xc0000a5460?, 0x18?, 0x14?, 0x0?)
        runtime/proc.go:363 +0xd6 fp=0xc00017df50 sp=0xc00017df30 pc=0x3abd16
runtime.gcBgMarkWorker()
        runtime/mgc.go:1235 +0xf1 fp=0xc00017dfe0 sp=0xc00017df50 pc=0x38cd11
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc00017dfe8 sp=0xc00017dfe0 pc=0x3d6b41
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1159 +0x25
 
goroutine 7 [GC worker (idle)]:
runtime.gopark(0x66b7d3aa16f5c?, 0xc0000a5480?, 0x18?, 0x14?, 0x0?)
        runtime/proc.go:363 +0xd6 fp=0xc000045f50 sp=0xc000045f30 pc=0x3abd16
runtime.gcBgMarkWorker()
        runtime/mgc.go:1235 +0xf1 fp=0xc000045fe0 sp=0xc000045f50 pc=0x38cd11
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc000045fe8 sp=0xc000045fe0 pc=0x3d6b41
created by runtime.gcBgMarkStartWorkers
        runtime/mgc.go:1159 +0x25
```

@samhocevar

### To Reproduce

To reproduce this bug, open Ikemen GO through the command line and keep it running in the background until it crashes.

### Expected behavior

Engine should keep running.

### Engine Version (or source code date)

Nightly (6/1/2023)

### Operating system

Windows

**Comment by Lazin3ss** [comment]
Update regarding this issue, I got the crash various times since I first reported it, and all of them had to do with raster text drawing. Seems there might be a correlation here.

**Comment by K4thos** [comment]
is this still happening?
