### ISSUE TITLE
crashlog 

### ISSUE THREAD

**Issue by iamno1one** [ikemen-engine/Ikemen-GO#1455]
### Describe the bug

game crashed 

### To Reproduce

random

### Engine Version (or source code date)

0.99 rc3

### Operating system

None

### Extra context or search terms

runtime error: index out of range [0] with length 0
goroutine 1 [running, locked to thread]:
github.com/yuin/gopher-lua.(*LState).PCall.func1()
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:1988 +0x212
panic({0x7ff7ed4b9040, 0xc002fe1968})
	C:/hostedtoolcache/windows/go/1.20.8/x64/src/runtime/panic.go:884 +0x213
main.PaletteToTexture({0x0, 0x0, 0xc001af66e0?})
	D:/a/Ikemen-GO/Ikemen-GO/src/image.go:310 +0x94
main.(*Sprite).CachePalette(0xc00846bea0, {0x0?, 0x0, 0xc0038f91d0?})
	D:/a/Ikemen-GO/Ikemen-GO/src/image.go:1028 +0x52
main.(*Layout).DrawSprite(0xc0060bb708, 0x27f?, 0x0?, 0x66e0?, 0xc00846bea0, 0x431f3fb3?, 0x3faaaaab, 0x0?)
	D:/a/Ikemen-GO/Ikemen-GO/src/common.go:634 +0xb3
main.(*LifeBarFace).draw(0xc0060bb000, 0x0?, 0x4, 0xc0027dd000)
	D:/a/Ikemen-GO/Ikemen-GO/src/lifebar.go:1112 +0x4b7
main.(*Lifebar).draw(0x7ff7ed43be00, 0x1)
	D:/a/Ikemen-GO/Ikemen-GO/src/lifebar.go:3955 +0xca5
main.(*System).draw(0x7ff7ed43bbc0, 0xc2c78000, 0x0, 0x3f800000)
	D:/a/Ikemen-GO/Ikemen-GO/src/system.go:1539 +0x2c9
main.(*System).fight(0x7ff7ed43bbc0)
	D:/a/Ikemen-GO/Ikemen-GO/src/system.go:2108 +0x1a75
main.systemScriptInit.func57.2()
	D:/a/Ikemen-GO/Ikemen-GO/src/script.go:979 +0x579
main.systemScriptInit.func57(0xc000228000)
	D:/a/Ikemen-GO/Ikemen-GO/src/script.go:1027 +0x3d3
github.com/yuin/gopher-lua.callGFunction(0xc000228000, 0x0)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/vm.go:202 +0x37
github.com/yuin/gopher-lua.init.3.func26(0xc000228000, 0xc0c0001?, 0xc00022a000?)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/vm.go:821 +0x379
github.com/yuin/gopher-lua.mainLoop(0xc000228000, 0xc0002b5e80?)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/vm.go:31 +0xfa
github.com/yuin/gopher-lua.(*LState).callR(0xc000228000, 0x0, 0xffffffffffffffff, 0xc000216128?)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:1211 +0x1b4
github.com/yuin/gopher-lua.(*LState).Call(...)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:1967
github.com/yuin/gopher-lua.(*LState).PCall(0xc000228000, 0x0, 0xc0002b5e80?, 0x0)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:2030 +0x145
github.com/yuin/gopher-lua.(*LState).DoFile(0xc000228000, {0xc000018930?, 0x0?})
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/auxlib.go:396 +0x6b
main.main()
	D:/a/Ikemen-GO/Ikemen-GO/src/main.go:90 +0x218

stack traceback:
	[G]: in function 'game'
	.\external\script\start.lua:1403: in function 'f_game'
	.\external\script\start.lua:1839: in function 'launchFight'
	external/script/default.lua:2: in function <external/script/default.lua:0>
	.\external\script\start.lua:1457: in function 'f'
	external/script/main.lua:3069: in function 'loop'
	external/script/main.lua:3189: in function 'loop'
	external/script/main.lua:4156: in main chunk
	[G]: ?

[Ikemen - Copy.log](https://github.com/ikemen-engine/Ikemen-GO/files/13113789/Ikemen.-.Copy.log)
[Ikemen.log](https://github.com/ikemen-engine/Ikemen-GO/files/13113790/Ikemen.log)

###############################################################################

**Comment by iamno1one** [comment]
[Ikemen.log](https://github.com/ikemen-engine/Ikemen-GO/files/13199680/Ikemen.log)

v0.99 crashlog

**Comment by iamno1one** [comment]
[Ikemen.log](https://github.com/ikemen-engine/Ikemen-GO/files/14261267/Ikemen.log)


i beleieve thihs may be due to redirects of explodes to partners, who exit/enter screen

**Comment by iamno1one** [comment]
ok some more feedback


im using explods to call anim and sprite from char, also adding a map and remove explod command,
add the below to a .zss on a clean build.

look at the timings on console and notice timing inconcistencies and also the remove explod command not executing at appropriate time.

i believe this is probably the cause of the crash logs posted before
[Ikemen_GO-v0.99.0-windows test.zip](https://github.com/ikemen-engine/Ikemen-GO/files/14266429/Ikemen_GO-v0.99.0-windows.test.zip)


as seen in video

https://youtu.be/_nkoFs7Lt8Y

**Comment by K4thos** [comment]
please let us know if it still happens on the latest nightly dev build
