### ISSUE TITLE
Ikemen go 99.0 stable version the true type font is not read in the system.sff

### ISSUE THREAD

**Issue by OldGamers** [ikemen-engine/Ikemen-GO#1715]
### Describe the bug

the error is posted on the `freetype: invalid TrueType format: bad kern table length
goroutine 1 [running, locked to thread]:
github.com/yuin/gopher-lua.(*LState).PCall.func1()
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:1988 +0x212
panic({0x7ff7a0f6a380, 0x7ff7a108d708})
	C:/hostedtoolcache/windows/go/1.20.10/x64/src/runtime/panic.go:884 +0x213
main.LoadFntTtf(0xc000389950, {0xc007c0e6c0?, 0x7ff7a0fd53c8?}, {0xc006f40a4b?, 0x7ff7a108d410?}, 0xffffffff)
	D:/a/Ikemen-GO/Ikemen-GO/src/util_desktop.go:49 +0x245
main.loadDefInfo(0xc000389950, {0xc007c0e6c0, 0x1f}, 0x7ff7a0fbf8e0?, 0x7490e08?)
	D:/a/Ikemen-GO/Ikemen-GO/src/font.go:308 +0x428
main.loadFntV2({0xc007c0e6c0, 0x1f}, 0xa0fd518c?)
	D:/a/Ikemen-GO/Ikemen-GO/src/font.go:271 +0x209
main.loadFnt({0xc007c0e6c0, 0x1f}, 0x7491048?)
	D:/a/Ikemen-GO/Ikemen-GO/src/font.go:52 +0x65
main.systemScriptInit.func56(0xc0001186e0)
	D:/a/Ikemen-GO/Ikemen-GO/src/script.go:844 +0x128
github.com/yuin/gopher-lua.callGFunction(0xc0001186e0, 0x0)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/vm.go:202 +0x37
github.com/yuin/gopher-lua.init.3.func26(0xc0001186e0, 0x60100a04?, 0xc0002050a0?)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/vm.go:821 +0x379
github.com/yuin/gopher-lua.mainLoop(0xc0001186e0, 0xc00816e840?)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/vm.go:31 +0xfa
github.com/yuin/gopher-lua.(*LState).callR(0xc0001186e0, 0x1, 0x1, 0xc000018ea0?)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:1211 +0x1b4
github.com/yuin/gopher-lua.(*LState).Call(...)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:1967
github.com/yuin/gopher-lua.loRequire(0xc0001186e0)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/baselib.go:564 +0x6d3
github.com/yuin/gopher-lua.callGFunction(0xc0001186e0, 0x0)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/vm.go:202 +0x37
github.com/yuin/gopher-lua.init.3.func26(0xc0001186e0, 0x34780600?, 0xc000205000?)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/vm.go:821 +0x379
github.com/yuin/gopher-lua.mainLoop(0xc0001186e0, 0xc000790740?)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/vm.go:31 +0xfa
github.com/yuin/gopher-lua.(*LState).callR(0xc0001186e0, 0x0, 0xffffffffffffffff, 0xc00000a7e8?)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:1211 +0x1b4
github.com/yuin/gopher-lua.(*LState).Call(...)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:1967
github.com/yuin/gopher-lua.(*LState).PCall(0xc0001186e0, 0x0, 0xc000790740?, 0x0)
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/state.go:2030 +0x145
github.com/yuin/gopher-lua.(*LState).DoFile(0xc0001186e0, {0xc000018918?, 0x0?})
	C:/Users/runneradmin/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20220504180219-658193537a64/auxlib.go:396 +0x6b
main.main()
	D:/a/Ikemen-GO/Ikemen-GO/src/main.go:90 +0x218

stack traceback:
	[G]: in function 'fontNew'
	external/script/main.lua:471: in function <external/script/main.lua:445>
	(tailcall): ?
	.\external\script\start.lua:1925: in function <.\external\script\start.lua:0>
	[G]: in function 'require'
	external/script/main.lua:2283: in main chunk
	[G]: ?
`
here the file attachment.
https://drive.google.com/file/d/188I0GoixIQ1LIcbyTm99_1fEkRpcZNAb/view?usp=sharing

### To Reproduce

just an issue with the fonts.

### Expected behavior

its crashing because. its will not ready the true type font

### Screenshots / Video

![Untitled](https://github.com/ikemen-engine/Ikemen-GO/assets/35203194/b5b1a97f-a06f-4caa-9725-37f28221d427)
this the cuase fo the issue

### Engine Version (or source code date)

v0.99.0

### Operating system

Windows

### Extra context or search terms

![Untitled](https://github.com/ikemen-engine/Ikemen-GO/assets/35203194/b1163bc8-f94f-44a2-b5e1-78f65e78a5c0)

**Comment by potsmugen** [comment]
Does the same font work in Mugen?

**Comment by bedlight** [comment]
> Does the same font work in Mugen?

i have the same exact issue and yes, the same font works on mugen

**Comment by SuperFromND** [comment]
Looked up the error message and it's possible this is a dependency problem rather than something in Ikemen GO: https://github.com/golang/freetype/issues/8

By chance, does this also happen in latest nightly?

**Comment by OldGamers** [comment]
> Looked up the error message and it's possible this is a dependency problem rather than something in Ikemen GO: [golang/freetype#8](https://github.com/golang/freetype/issues/8)
> 
> By chance, does this also happen in latest nightly?

yes its does happed also on the Nightly as well :o I don't know why but its rejecting the fonts that why I send the downloads link for the screen pack so everyone here can see the issue as well. hoping for an answer. I was trying to convert a screen pack for a friend and this is one those screen pack wont set well with the ikemen go 99.0 :o

**Comment by OldGamers** [comment]
> Does the same font work in Mugen?

yes its work good on mugen with no issue. I checked and made sure that they were TTF type fonts but the problem is that Ikemen go 99.0 and nightly does not like the way the fonts is reading.

**Comment by SuperFromND** [comment]
I've at least narrowed it down to the specific font causing the problem, it's `njnaruto.ttf`. I've attached it below:
[njnaruto.zip](https://github.com/ikemen-engine/Ikemen-GO/files/14823547/njnaruto.zip)

This font can also be obtained from [here](https://www.dafont.com/ninja-naruto.font) (labelled as "100% free", so linking this should be fine).

**Comment by shinriyo** [comment]
```
Last login: Thu Jul 11 14:56:17 on ttys003
/Users/shinriyo/Downloads/Ikemen_GO-v0.99.0-macos/Ikemen_GO_MacOS ; exit;
(base) ~ % /Users/shinriyo/Downloads/Ikemen_GO-v0.99.0-macos/Ikemen_GO_MacOS ; exit;
panic: Main lua file "external/script/main.lua" error.
open external/script/main.lua: no such file or directory

goroutine 1 [running, locked to thread]:
main.main()
	/Users/runner/work/Ikemen-GO/Ikemen-GO/src/main.go:80 +0x529

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]


```

**Comment by shinriyo** [comment]
<img width="644" alt="Screenshot 2024-07-11 at 15 00 10" src="https://github.com/ikemen-engine/Ikemen-GO/assets/396927/dce432b7-e24e-4b33-a10d-a1ac3fd8a200">
Actually it exists

**Comment by shinriyo** [comment]
Finally I could open.

```
cd /Users/shinriyo/Downloads/Ikemen_GO-v0.99.0-macos
./Ikemen_GO_MacOS
```
not open Ikemen_GO_MacOS by click.

**Comment by K4thos** [comment]
> I've at least narrowed it down to the specific font causing the problem, it's `njnaruto.ttf`. I've attached it below: [njnaruto.zip](https://github.com/ikemen-engine/Ikemen-GO/files/14823547/njnaruto.zip)
> 
> This font can also be obtained from [here](https://www.dafont.com/ninja-naruto.font) (labelled as "100% free", so linking this should be fine).

the freetype repo was archived, so the fix is unlikely. I will add a workaround to strip bad kern table directly to the engine
